


static std::map<std::pair<uint32_t,uint32_t>, bool> g_discoveryAcked;
static std::map<std::pair<uint32_t,uint32_t>, uint32_t> g_discoveryRetries;
static const uint32_t MAX_DISCOVERY_RETRIES = 3;
static const double DISCOVERY_ACK_TIMEOUT = 2.0; 
uint32_t seed = ns3::RngSeedManager::GetSeed(); 
uint32_t runNumber = 1;       
std::string routing;
std::string scenarioId ;   
std::string routingsize;
static std::unordered_set<uint32_t> assignedSarNodes;
std::map<uint32_t, bool> g_civilianAttachedState; 
static std::unordered_map<uint32_t, Vector> sarToCivilianOffset;
bool g_activeFound = false;            
Time g_lastActiveTime = Seconds(0.0);  
double g_noActiveTimeout = 5.0;        
double convergenceThresholdDistance = 12.0;  
double sarProxmitytoBase = 22.0; 
double civilianProxmitytoBase = 12.0; 
NodeContainer sarNodes, allSarNodes,groundNodes,civilianNodes,civilianNodesquery,allNodes;
static std::vector<std::string> energyBuffer;
static std::vector<std::string> phyRxBuffer;
Ptr<Socket> baseBroadcastSocket;
Ptr<Socket> baseStationSocket;
uint16_t broadcastPort = 8000;
uint16_t convergencePort = 9000;      
uint16_t rescuemovmentport = 8200;
uint16_t voicePort = 6000;
uint16_t CivilianSafePort = 8300;
uint16_t assignmentPort = 8100;       
uint16_t discoveryPort = 7000;          
uint16_t discoveryAckPort = 7101;
uint16_t sarDiscoveryPort=7002;      
uint16_t discoverybasePort=7001;       
uint16_t controlMsgPort= 8081;
uint16_t PLBPort = 9100;   
uint16_t WificivilianPort= 9200;
uint16_t QueryResponsePort= 9300;
uint16_t SARcivilianqueryport= 9400;
uint16_t envPort = 6001;
uint16_t videoPort = 5000;  
uint16_t gpsPort = 10; 
uint32_t comm=0;
static std::unordered_set<uint32_t> pendingCivilians;
static std::map<uint32_t, double> g_nodeSpeedSum; 
static std::map<uint32_t, uint64_t> g_nodeSpeedCount;
Ptr<Node> g_baseNode;
std::vector<Ptr<Node>> g_sarNodes;
std::map<uint32_t, uint32_t> g_civilianToSarNodeMap; 
std::ofstream movementLogFile; 
std::ofstream rescueCompletionLogFile; 
std::ofstream receivedAssignmentsLogFile;
std::ofstream convergenceLogFile;
std::ofstream positionLogFile; 
std::ofstream pendingAssignmentCsv;
std::ofstream gpsLogFile;
std::ofstream signalLogFile;
std::ofstream connectionLogFile;
std::ofstream videoLogFile;       
std::ofstream packetLogFile; 
std::ofstream voiceLogFile("voice_communication_logfinalv3.csv"); 
std::map<uint32_t, double> sendTimestamps;  
std::ofstream envLogFile("environmental_data_logfinalv3.csv"); 
std::ofstream discoveryLogFile; 
std::unordered_map<uint32_t, std::unordered_map<uint32_t, bool>> discoveryState;
static std::map<std::pair<uint32_t, uint32_t>, Vector> lastLoggedPosition;
std::ofstream centralDiscoveryLogFile;
std::ofstream sarDiscoveryBroadcastLogFile;
std::unordered_map<uint32_t, Vector> lastKnownPositions; 
std::unordered_map<uint32_t, uint32_t> rescueAssignments; 
std::ofstream rescueAssignmentLogFile; 
std::ofstream attachmentLogFile;
std::ofstream macTxRxLogFile;
static const double EPS = 1e-7; 
std::ofstream routingLogFile;
std::ofstream systemLogFile;
std::map<std::pair<uint32_t, uint32_t>, uint32_t> sessionTable; 
uint32_t voiceCommunicationId = 5000; 
uint32_t sartosarCommunicationId=6000;
uint32_t nextBroadcastCommId = 60000; 
std::map<uint32_t, bool> civilianSafetyStatus;
std::map<std::tuple<uint32_t, Ipv4Address, Ipv4Address, std::string>, uint32_t> sessionsignalTable;
uint32_t nextCommId = 3000;
static std::map<uint32_t, std::vector<Vector>> trackedConvergencePositions;
static std::map<uint32_t, std::vector<Vector>> sarPreviousPositions;
static double scenarioStartTime;
